[project]
name = "mgcom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "notebook>=7.2.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
